name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
      NEW_VERSION: ${{ steps.version.outputs.version }}
      
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
  
    - name: Docker login
      run: | 
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
        echo "New version: $NEW_VERSION !!!!!"
        
    # - name: Build the Docker image
    #   run: |
    #     docker build  --build-arg APP_VERSION=0.0.2 -t $DOCKER_USER/$DOCKER_CONTAINER_NAME:0.0.2 .
    #     docker build  --build-arg APP_VERSION=0.0.2 -t $DOCKER_USER/$DOCKER_CONTAINER_NAME:latest .
        
    # - name: Push Docker Image
    #   run: |
    #     docker push $DOCKER_USER/$DOCKER_CONTAINER_NAME:0.0.2
    #     docker push $DOCKER_USER/$DOCKER_CONTAINER_NAME:latest
    #  # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
